matrix:
  include:
    - language: go
      go: 1.8.x
      sudo: required
      install:
        - go get -u golang.org/x/lint/golint
        - curl https://glide.sh/get | bash
        - sudo pip install pre-commit
      script:
        - rm -f .copyright.hook && wget https://raw.githubusercontent.com/PaddlePaddle/Paddle/develop/tools/codestyle/copyright.hook
        - bash -x .tools/check_style.sh
        - ln -s $GOPATH/src/github.com/PaddlePaddle $GOPATH/src/github.com/paddlepaddle
        - cd $GOPATH/src/github.com/paddlepaddle/edl
        - glide install --strip-vendor
        - go test $(glide novendor)
